# Generated by Django 3.2.15 on 2022-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
